
export enum ActionType {
  CREATE_ARTICLE = "CREATE_ARTICLE",
  UPDATE_ARTICLE = "UPDATE_ARTICLE",
  DELETE_ARTICLE = "DELETE_ARTICLE",
  RETRIEVE_ARTICLES = "RETRIEVE_ARTICLES",

  CREATE_CATEGORY = "CREATE_CATEGORY",
  UPDATE_CATEGORY = "UPDATE_CATEGORY",
  DELETE_CATEGORY = "DELETE_CATEGORY",
  RETRIEVE_CATEGORIES = "RETRIEVE_CATEGORIES",

  CREATE_DEPARTMENT = "CREATE_DEPARTMENT",
  UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT",
  DELETE_DEPARTMENT = "DELETE_DEPARTMENT",
  RETRIEVE_DEPARTMENTS = "RETRIEVE_DEPARTMENTS"
}
